name: 'deps: Bump Golang version'
pipelineid: golang/version

scm:
  env_token: UPDATECLI_GITHUB_TOKEN
  username: harvester-bot
  user: harvester-bot
  email: harvester-bot@users.noreply.github.com
  commitType: chore
  commitScope: golang
  footer: "Signed-off-by: harvester-bot <harvester-bot@users.noreply.github.com>"

actions:
  reviewers:
    - harvester/dev
  labels:
    - golang
    - dependency

docker:
  matcher: "registry.suse.com/bci/golang"